INSERT INTO series(title) VALUES ('Harry Potter');
INSERT INTO series(title) VALUES ('Eragon');
INSERT INTO subgenres(name) VALUES ('Magical');
INSERT INTO subgenres(name) VALUES ('YA');
INSERT INTO authors(name) VALUES ('J.K. Rolling');
INSERT INTO authors(name) VALUES ('Christopher Paolini');
INSERT INTO books(title) VALUES ("The Sorcerer's Stone");
INSERT INTO books(title) VALUES ("The Chamber of Secrets");
INSERT INTO books(title) VALUES ('The Prisoner of Azkaban');
INSERT INTO books(title) VALUES ('Eragon');
INSERT INTO books(title) VALUES ('Eldest');
INSERT INTO books(title) VALUES ('Brisingr');
INSERT INTO characters(name) VALUES ('Harry');
INSERT INTO characters(name) VALUES ('Sirius');
INSERT INTO characters(name) VALUES ('Hermione');
INSERT INTO characters(name) VALUES ('Wormtail');
INSERT INTO characters(name) VALUES ('Eragon');
INSERT INTO characters(name) VALUES ('Saphira');
INSERT INTO characters(name) VALUES ('Brom');
INSERT INTO characters(name) VALUES ('Thorn');
INSERT INTO character_books(character_id,book_id) VALUES (1,1);
INSERT INTO character_books(character_id,book_id) VALUES (1,2);
INSERT INTO character_books(character_id,book_id) VALUES (1,3);
INSERT INTO character_books(character_id,book_id) VALUES (2,3);
INSERT INTO character_books(character_id,book_id) VALUES (3,1);
INSERT INTO character_books(character_id,book_id) VALUES (3,2);
INSERT INTO character_books(character_id,book_id) VALUES (3,3);
INSERT INTO character_books(character_id,book_id) VALUES (4,3);
INSERT INTO character_books(character_id,book_id) VALUES (5,4);
INSERT INTO character_books(character_id,book_id) VALUES (5,5);
INSERT INTO character_books(character_id,book_id) VALUES (5,6);
INSERT INTO character_books(character_id,book_id) VALUES (6,4);
INSERT INTO character_books(character_id,book_id) VALUES (6,5);
INSERT INTO character_books(character_id,book_id) VALUES (6,6);
INSERT INTO character_books(character_id,book_id) VALUES (7,6);
INSERT INTO character_books(character_id,book_id) VALUES (8,5);